# Generated by Django 5.2.1 on 2025-05-11 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FoodLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("feeddatetime", models.DateTimeField()),
                ("food_qty", models.IntegerField()),
                ("water_qty", models.IntegerField()),
            ],
            options={
                "db_table": "foodlog",
            },
        ),
    ]
