# Generated by Django 5.2.1 on 2025-06-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodtracker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="foodlog",
            name="teeth_brush",
            field=models.BooleanField(default=False),
        ),
    ]
